In [1]:
import numpy as np

arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [3]:
arr2=np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr2)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [4]:
arr3=np.zeros((2,2))
print(arr3)

[[0. 0.]
 [0. 0.]]


In [6]:
arr4=np.ones((2,3))
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
arr5=np.random.randint(1,20,5)
print(arr5)

[16  8 18  5  8]


In [16]:
arr4=np.random.randint(1,30,4).reshape(-1,2)
print(arr4)

[[ 8 18]
 [10 26]]


In [17]:
print(arr[1:4])


[20 30 40]


In [18]:
print(arr2.shape)

(3, 3)


In [19]:
print(arr4.T)

[[ 8 10]
 [18 26]]


In [24]:
print(np.mean(arr))

30.0


In [23]:
print(np.median(arr))

30.0


In [28]:
import numpy as np
from scipy import stats
arra=np.array([10,20,40,40,20])
print(stats.mode(arra))

ModeResult(mode=np.int64(20), count=np.int64(2))


In [29]:
print(np.var(arr))

144.0


In [30]:
print(np.std(arr))

12.0


In [32]:
ar1=np.array([23,56,12,90,34,18,10])
print(np.sort(ar1))

[10 12 18 23 34 56 90]


In [33]:
ar2=np.array([[12,89,34],[23,49,29],[67,89,30]])
print(ar2)

[[12 89 34]
 [23 49 29]
 [67 89 30]]


In [34]:
print(np.sort(ar2,axis=0))

[[12 49 29]
 [23 89 30]
 [67 89 34]]


In [35]:
print(np.sort(ar2,axis=1))

[[12 34 89]
 [23 29 49]
 [30 67 89]]


In [36]:
ar3=np.array([[12,90,34],[25,78,90],[23,12,10]])
print(ar3)

[[12 90 34]
 [25 78 90]
 [23 12 10]]


In [37]:
mat_mul=np.array(ar2*ar3)
print(mat_mul)

[[ 144 8010 1156]
 [ 575 3822 2610]
 [1541 1068  300]]


In [38]:
mat_add=np.array(ar2+ar3)
print(mat_add)

[[ 24 179  68]
 [ 48 127 119]
 [ 90 101  40]]


In [42]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
concat=np.concatenate((a1,a2))
print(concat)

[1 2 3 4 5 6]


In [43]:
print(np.unique(concat))

[1 2 3 4 5 6]


In [45]:
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [50]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
data=np.array([12,38,90,89,23,10,4,76])
print(np.argmin(data))

6


In [52]:
print(data[6])

4


In [53]:
print(np.argmax(data))

2


In [54]:
print(data[2])

90


In [58]:
print(np.where(data>=40))
# to get actual values instead of index
print(data[data>=40])

(array([2, 3, 7]),)
[90 89 76]


In [60]:
print(np.cumsum(data))

[ 12  50 140 229 252 262 266 342]


In [62]:
print(np.corrcoef(a1,a2))
# +1 = strong  positive correlation
#-1 = strong negative correlation

[[1. 1.]
 [1. 1.]]


In [66]:
new_data=np.arange(1,11,1)
print(new_data)

[ 1  2  3  4  5  6  7  8  9 10]


In [67]:
np.save("new_data.npy",new_data)
loaded=np.load("new_data.npy")
print(loaded)

[ 1  2  3  4  5  6  7  8  9 10]
